controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - actuator_forearm_joint
      - base_block_rotating_block_joint
      - rotating_block_vertical_arm_joint
      - vertical_arm_forearm_joint
     
