controller_list:
  - name: fake_arm_controller
    type: $(arg execution_type)
    joints:
      - base_block_rotating_block_joint
      - rotating_block_vertical_arm_joint
      - vertical_arm_forearm_joint
      - actuator_forearm_joint
  - name: fake_gripper_controller
    type: $(arg execution_type)
    joints:
      - left_gripper_actuator_body
      - right_gripper_actuator_body
initial:  # Define initial robot poses.
  - group: arm
    pose: initial_pose
  - group: gripper
    pose: gripper_open